### ISSUE TITLE
cant clone formio repo

### ISSUE THREAD

**Issue by sp-7indigo** [tiredofit/docker-formio-api#1]
https://github.com/tiredofit/docker-formio/blob/053d7eeb2ff6c8b56b4b1e641b285dc695544793/api/install/etc/cont-init.d/10-nodejs#L38

you can't clone because directory is not empty due to user creation on base image  tiredofit/nodejs

https://github.com/tiredofit/docker-nodejs/blob/49b4d2978b754e2d5de70403b8eaa085d891a4a7/9/debian/Dockerfile#L9

**Comment by tiredofit** [comment]
Sorry for delay. Fixed now, with an all new optimized release.
